# fly.toml app configuration file generated for pokedex-lauri on 2023-05-19T23:14:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-lauri"
primary_region = "arn"

[build]
  [build.args]
    NODE_VERSION = "16.20.0"

[env]
  PORT = "8080"

[processes]
  app = "node app.js"

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = false


  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "60s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]