# fly.toml app configuration file generated for pokedex-lauri on 2023-05-19T23:14:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokedex-lauri"
primary_region = "arn"

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
[env]
  PORT = "8080"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[[services]]
  processes = ["app"]

[build]
  [build.args]
    NODE_VERSION = "16.20.0"

[experimental]
  auto_rollback = true